version: '3'
services:
  docker-my:
    image: mysq:latest
    ports:
      - "3308:3306"
    restart: always
    container_name: docker-my
    environment:
      MYSQL_DATABASE: air-companies
      MYSQL_USER: root
      MYSQL_PASSWORD: 61hovumo
      MYSQL_ROOT_PASSWORD: root

  air-companies:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    restart: always
    depends_on:
      - docker-my